//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeHealthy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeHealthyEntities1 : DbContext
    {
        public BeHealthyEntities1()
            : base("name=BeHealthyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiefComplaints> ChiefComplaints { get; set; }
        public virtual DbSet<DietarySupplement> DietarySupplement { get; set; }
        public virtual DbSet<Dietitian> Dietitian { get; set; }
        public virtual DbSet<Disorder> Disorder { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<ExaminationType> ExaminationType { get; set; }
        public virtual DbSet<Medecine> Medecine { get; set; }
        public virtual DbSet<MedicalRecord> MedicalRecord { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Organ> Organ { get; set; }
        public virtual DbSet<Physical_Examination> Physical_Examination { get; set; }
        public virtual DbSet<Symptoms> Symptoms { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
