//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeHealthy.Models
{
    //額外using這兩個
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class ChiefComplaints
    {
        [Key]
        [DisplayName("主訴編號")]
        [Required]
        public int ChiefComplaintsID { get; set; }  //這是欄位去封裝而成的屬性
        [DisplayName("症狀編號")]
        [Required]
        public string SymptomID { get; set; }
        [DisplayName("主訴單建立日期")]
        [Required]  //讓系統自動取得時間
        [DataType(DataType.DateTime)]//這裡是給View表單欄位看的
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd hh:mm:ss}")] //指定想要顯示日期時間格式
      
        public System.DateTime ChiefComplaintsDATE { get; set; }
        [DisplayName("醫囑")]
        public string DoctorORDER { get; set; }

        [DisplayName("醫師編號")]
        public string DoctorID { get; set; }

        [DisplayName("營養師建議")]
        public string DietitianORDER { get; set; }

        [DisplayName("營養師編號")]
        public string DietitianID { get; set; }
       
        [DisplayName("簡述身體不適:")]
        public string Details { get; set; }
       
        [DisplayName("會員帳號")]
        [Required(ErrorMessage = "請填寫會員編號")]
        public string MemberID { get; set; }

        public virtual Symptoms Symptoms { get; set; }
    }
}
