//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeHealthy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medecine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medecine()
        {
            this.MedicalRecord = new HashSet<MedicalRecord>();
        }
    
        public string MedecineID { get; set; }
        public string DisorderID { get; set; }
        public string MedecineENAME { get; set; }
        public string MedecineCNAME { get; set; }
        public string MedecineLICENSE { get; set; }
        public string MedecineINTRO { get; set; }
        public string SymptomID { get; set; }
    
        public virtual Symptoms Symptoms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalRecord> MedicalRecord { get; set; }
    }
}
