//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeHealthy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecord
    {
        public int MedicalRecordID { get; set; }
        public string MedecineID { get; set; }
        public string DisorderID { get; set; }
        public string MemberID { get; set; }
        public System.DateTime MedicalRecordDATE { get; set; }
        public string DoctorID { get; set; }
    
        public virtual Disorder Disorder { get; set; }
        public virtual Medecine Medecine { get; set; }
        public virtual Members Members { get; set; }
    }
}
