//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeHealthy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Members()
        {
            this.MedicalRecord = new HashSet<MedicalRecord>();
        }

        [Key]
        [DisplayName("會員帳號")]
        [Required]
        public string MemberID { get; set; }

        [DisplayName("會員姓名")]
        [Required]
        public string MemberName { get; set; }

        [DisplayName("會員電話")]
        [Required]
        public string MemberPHONE { get; set; }

        [DisplayName("會員信箱")]
        [Required]
        public string MemberEMAIL { get; set; }

        [DisplayName("會員生日")]
        public Nullable<System.DateTime> MemberBIRTHDAY { get; set; }

        [DisplayName("會員年齡")]
        public Nullable<byte> MemberAGE { get; set; }

        [DisplayName("會員性別")]
        public bool MemberGENDER { get; set; }

        [DisplayName("會員密碼")]
        [Required]
        [DataType(DataType.Password)]
        [MinLength(8, ErrorMessage = "密碼長度最少八碼")]
        [MaxLength(12, ErrorMessage = "密碼長度最多12碼")]
        public string MemberPASSWORD { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalRecord> MedicalRecord { get; set; }
    }
}
