//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeHealthy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptoms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Symptoms()
        {
            this.ChiefComplaints = new HashSet<ChiefComplaints>();
            this.Medecine = new HashSet<Medecine>();
        }
    
        public string SymptomID { get; set; }
        public string SymptomENAME { get; set; }
        public string SymptomCNAME { get; set; }
        public string OrganID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiefComplaints> ChiefComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medecine> Medecine { get; set; }
    }
}
